default_enabled = {
    "head_joint_enabled": False,
    "neck_joint_enabled": False,    
    "chest_joint_enabled": True,
    "spine_upper_joint_enabled": False,
    "spine_middle_joint_enabled": False,
    "spine_lower_joint_enabled": False,
    "hips_joint_enabled": True,
    "left_shoulder_joint_enabled": False,
    "left_scapula_joint_enabled": False,
    "left_arm_upper_joint_enabled": True,
    "left_arm_lower_joint_enabled": True,
    "left_hand_wrist_twist_joint_enabled": False,
    "left_hand_wrist_joint_enabled": False,
    "left_upper_leg_joint_enabled": False,
    "left_lower_leg_joint_enabled": True,
    "left_foot_ankle_twist_joint_enabled": False,
    "left_foot_ankle_joint_enabled": False,
    "left_foot_subtalar_joint_enabled": False,
    "left_foot_transverse_joint_enabled": True,
    "left_foot_ball_joint_enabled": False,
    "right_shoulder_joint_enabled": False,
    "right_scapula_joint_enabled": False,
    "right_arm_upper_joint_enabled": True,
    "right_arm_lower_joint_enabled": True,
    "right_hand_wrist_twist_joint_enabled": False,
    "right_hand_wrist_joint_enabled": False,
    "right_upper_leg_joint_enabled": False,
    "right_lower_leg_joint_enabled": True,
    "right_foot_ankle_twist_joint_enabled": False,
    "right_foot_ankle_joint_enabled": False,
    "right_foot_subtalar_joint_enabled": False,
    "right_foot_transverse_joint_enabled": True,
    "right_foot_ball_joint_enabled": False
}

default_offsets = {
    "head_joint_offset_x": 0.0,
    "head_joint_offset_y": 0.0,
    "head_joint_offset_z": 0.0,
    "head_joint_rot_x": 90.0,
    "head_joint_rot_y": 0.0,
    "head_joint_rot_z": 0.0,
    "neck_joint_offset_x": 0.0,
    "neck_joint_offset_y": 0.0,
    "neck_joint_offset_z": 0.0,
    "neck_joint_rot_x": 90.0,
    "neck_joint_rot_y": 0.0,
    "neck_joint_rot_z": 0.0,
    "chest_joint_offset_x": 0.03,
    "chest_joint_offset_y": 0.0,
    "chest_joint_offset_z": -0.13,
    "chest_joint_rot_x": 90.0,
    "chest_joint_rot_y": 0.0,
    "chest_joint_rot_z": 0.0,
    "spine_upper_joint_offset_x": 0.0,
    "spine_upper_joint_offset_y": 0.0,
    "spine_upper_joint_offset_z": 0.0,
    "spine_upper_joint_rot_x": 90.0,
    "spine_upper_joint_rot_y": 0.0,
    "spine_upper_joint_rot_z": 0.0,
    "spine_middle_joint_offset_x": 0.0,
    "spine_middle_joint_offset_y": 0.0,
    "spine_middle_joint_offset_z": 0.0,
    "spine_middle_joint_rot_x": 90.0,
    "spine_middle_joint_rot_y": 0.0,
    "spine_middle_joint_rot_z": 0.0,
    "spine_lower_joint_offset_x": 0.0,
    "spine_lower_joint_offset_y": 0.0,
    "spine_lower_joint_offset_z": 0.0,
    "spine_lower_joint_rot_x": 90.0,
    "spine_lower_joint_rot_y": 0.0,
    "spine_lower_joint_rot_z": 0.0,
    "hips_joint_offset_x": 0.0,
    "hips_joint_offset_y": 0.0,
    "hips_joint_offset_z": -0.1,
    "hips_joint_rot_x": 90.0,
    "hips_joint_rot_y": 0.0,
    "hips_joint_rot_z": 0.0,
    "left_shoulder_joint_offset_x": 0.0,
    "left_shoulder_joint_offset_y": 0.0,
    "left_shoulder_joint_offset_z": 0.0,
    "left_shoulder_joint_rot_x": 180.0,
    "left_shoulder_joint_rot_y": 0.0,
    "left_shoulder_joint_rot_z": 0.0,
    "left_scapula_joint_offset_x": 0.0,
    "left_scapula_joint_offset_y": 0.0,
    "left_scapula_joint_offset_z": 0.0,
    "left_scapula_joint_rot_x": 180.0,
    "left_scapula_joint_rot_y": 0.0,
    "left_scapula_joint_rot_z": 0.0,
    "left_arm_upper_joint_offset_x": 0.13,
    "left_arm_upper_joint_offset_y": 0.0,
    "left_arm_upper_joint_offset_z": 0.0,
    "left_arm_upper_joint_rot_x": 0.0,
    "left_arm_upper_joint_rot_y": 180.0,
    "left_arm_upper_joint_rot_z": 0.0,
    "left_arm_lower_joint_offset_x": 0.13,
    "left_arm_lower_joint_offset_y": 0.0,
    "left_arm_lower_joint_offset_z": 0.0,
    "left_arm_lower_joint_rot_x": 0.0,
    "left_arm_lower_joint_rot_y": 180.0,
    "left_arm_lower_joint_rot_z": 0.0,
    "left_hand_wrist_twist_joint_offset_x": 0.0,
    "left_hand_wrist_twist_joint_offset_y": 0.0,
    "left_hand_wrist_twist_joint_offset_z": 0.0,
    "left_hand_wrist_twist_joint_rot_x": 180.0,
    "left_hand_wrist_twist_joint_rot_y": 0.0,
    "left_hand_wrist_twist_joint_rot_z": 0.0,
    "left_hand_wrist_joint_offset_x": 0.0,
    "left_hand_wrist_joint_offset_y": 0.0,
    "left_hand_wrist_joint_offset_z": 0.0,
    "left_hand_wrist_joint_rot_x": -90.0,
    "left_hand_wrist_joint_rot_y": 0.0,
    "left_hand_wrist_joint_rot_z": 0.0,
    "left_upper_leg_joint_offset_x": 0.0,
    "left_upper_leg_joint_offset_y": 0.0,
    "left_upper_leg_joint_offset_z": 0.0,
    "left_upper_leg_joint_rot_x": -90.0,
    "left_upper_leg_joint_rot_y": 0.0,
    "left_upper_leg_joint_rot_z": 0.0,
    "left_lower_leg_joint_offset_x": 0.0,
    "left_lower_leg_joint_offset_y": 0.0,
    "left_lower_leg_joint_offset_z": 0.0,
    "left_lower_leg_joint_rot_x": -90.0,
    "left_lower_leg_joint_rot_y": 0.0,
    "left_lower_leg_joint_rot_z": 0.0,
    "left_foot_ankle_twist_joint_offset_x": 0.0,
    "left_foot_ankle_twist_joint_offset_y": 0.0,
    "left_foot_ankle_twist_joint_offset_z": 0.0,
    "left_foot_ankle_twist_joint_rot_x": 0.0,
    "left_foot_ankle_twist_joint_rot_y": 0.0,
    "left_foot_ankle_twist_joint_rot_z": 0.0,
    "left_foot_ankle_joint_offset_x": 0.0,
    "left_foot_ankle_joint_offset_y": 0.0,
    "left_foot_ankle_joint_offset_z": 0.0,
    "left_foot_ankle_joint_rot_x": 0.0,
    "left_foot_ankle_joint_rot_y": -90.0,
    "left_foot_ankle_joint_rot_z": 0.0,
    "left_foot_subtalar_joint_offset_x": 0.0,
    "left_foot_subtalar_joint_offset_y": 0.0,
    "left_foot_subtalar_joint_offset_z": 0.0,
    "left_foot_subtalar_joint_rot_x": 0.0,
    "left_foot_subtalar_joint_rot_y": 0.0,
    "left_foot_subtalar_joint_rot_z": 0.0,
    "left_foot_transverse_joint_offset_x": 0.0,
    "left_foot_transverse_joint_offset_y": 0.0,
    "left_foot_transverse_joint_offset_z": 0.0,
    "left_foot_transverse_joint_rot_x": 90.0,
    "left_foot_transverse_joint_rot_y": -90.0,
    "left_foot_transverse_joint_rot_z": 0.0,
    "left_foot_ball_joint_offset_x": 0.0,
    "left_foot_ball_joint_offset_y": 0.0,
    "left_foot_ball_joint_offset_z": 0.0,
    "left_foot_ball_joint_rot_x": 0.0,
    "left_foot_ball_joint_rot_y": 0.0,
    "left_foot_ball_joint_rot_z": 0.0,
    "right_shoulder_joint_offset_x": 0.0,
    "right_shoulder_joint_offset_y": 0.0,
    "right_shoulder_joint_offset_z": 0.0,
    "right_shoulder_joint_rot_x": 0.0,
    "right_shoulder_joint_rot_y": 0.0,
    "right_shoulder_joint_rot_z": 0.0,
    "right_scapula_joint_offset_x": 0.0,
    "right_scapula_joint_offset_y": 0.0,
    "right_scapula_joint_offset_z": 0.0,
    "right_scapula_joint_rot_x": 0.0,
    "right_scapula_joint_rot_y": 0.0,
    "right_scapula_joint_rot_z": 0.0,
    "right_arm_upper_joint_offset_x": 0.13,
    "right_arm_upper_joint_offset_y": 0.0,
    "right_arm_upper_joint_offset_z": 0.0,
    "right_arm_upper_joint_rot_x": 0.0,
    "right_arm_upper_joint_rot_y": 0.0,
    "right_arm_upper_joint_rot_z": 0.0,
    "right_arm_lower_joint_offset_x": 0.13,
    "right_arm_lower_joint_offset_y": 0.0,
    "right_arm_lower_joint_offset_z": 0.0,
    "right_arm_lower_joint_rot_x": 0.0,
    "right_arm_lower_joint_rot_y": 0.0,
    "right_arm_lower_joint_rot_z": 0.0,
    "right_hand_wrist_twist_joint_offset_x": 0.0,
    "right_hand_wrist_twist_joint_offset_y": 0.0,
    "right_hand_wrist_twist_joint_offset_z": 0.0,
    "right_hand_wrist_twist_joint_rot_x": 0.0,
    "right_hand_wrist_twist_joint_rot_y": 0.0,
    "right_hand_wrist_twist_joint_rot_z": 0.0,
    "right_hand_wrist_joint_offset_x": 0.0,
    "right_hand_wrist_joint_offset_y": 0.0,
    "right_hand_wrist_joint_offset_z": 0.0,
    "right_hand_wrist_joint_rot_x": 90.0,
    "right_hand_wrist_joint_rot_y": 0.0,
    "right_hand_wrist_joint_rot_z": 0.0,
    "right_upper_leg_joint_offset_x": 0.0,
    "right_upper_leg_joint_offset_y": 0.0,
    "right_upper_leg_joint_offset_z": 0.0,
    "right_upper_leg_joint_rot_x": 90.0,
    "right_upper_leg_joint_rot_y": 0.0,
    "right_upper_leg_joint_rot_z": 0.0,
    "right_lower_leg_joint_offset_x": 0.0,
    "right_lower_leg_joint_offset_y": 0.0,
    "right_lower_leg_joint_offset_z": 0.0,
    "right_lower_leg_joint_rot_x": 90.0,
    "right_lower_leg_joint_rot_y": 0.0,
    "right_lower_leg_joint_rot_z": 0.0,
    "right_foot_ankle_twist_joint_offset_x": 0.0,
    "right_foot_ankle_twist_joint_offset_y": 0.0,
    "right_foot_ankle_twist_joint_offset_z": 0.0,
    "right_foot_ankle_twist_joint_rot_x": 0.0,
    "right_foot_ankle_twist_joint_rot_y": 180.0,
    "right_foot_ankle_twist_joint_rot_z": 0.0,
    "right_foot_ankle_joint_offset_x": 0.0,
    "right_foot_ankle_joint_offset_y": 0.0,
    "right_foot_ankle_joint_offset_z": 0.0,
    "right_foot_ankle_joint_rot_x": 0.0,
    "right_foot_ankle_joint_rot_y": 90.0,
    "right_foot_ankle_joint_rot_z": 0.0,
    "right_foot_subtalar_joint_offset_x": 0.0,
    "right_foot_subtalar_joint_offset_y": 0.0,
    "right_foot_subtalar_joint_offset_z": 0.0,
    "right_foot_subtalar_joint_rot_x": 0.0,
    "right_foot_subtalar_joint_rot_y": 180.0,
    "right_foot_subtalar_joint_rot_z": 0.0,
    "right_foot_transverse_joint_offset_x": 0.0,
    "right_foot_transverse_joint_offset_y": 0.0,
    "right_foot_transverse_joint_offset_z": 0.0,
    "right_foot_transverse_joint_rot_x": -90.0,
    "right_foot_transverse_joint_rot_y": 90.0,
    "right_foot_transverse_joint_rot_z": 0.0,
    "right_foot_ball_joint_offset_x": 0.0,
    "right_foot_ball_joint_offset_y": 0.0,
    "right_foot_ball_joint_offset_z": 0.0,
    "right_foot_ball_joint_rot_x": 0.0,
    "right_foot_ball_joint_rot_y": 180.0,
    "right_foot_ball_joint_rot_z": 0.0
}

default_misc_toggles = {
    "disable_knuckles_rendermodels": False,
    "use_trackpad_thumb": False
}

default_misc = {
    "thumb_curl_threshold": 0.45,
    "thumb_curl_full_threshold": 0.7,
    "other_fingers_curl_threshold": 0.075,
    "index_curl_touch_threshold": 0.45,
    "trigger_touch_curl_value": 0.2,
    "trigger_click_threshold_hand": 0.5,
    "trigger_click_threshold_controller": 0.8,
    "grip_pinky_curl_threshold": 0.0,
    "grip_ring_curl_threshold": 0.1,
    "grip_middle_curl_threshold": 0.2,
    "grip_force_threshold_hand": 0.3,
    "grip_force_threshold_controller": 0.7,
    "hysteresis": 0.15
}

tooltips_enabled = {
    "head_joint_enabled": "Not recommended, default OFF",
    "neck_joint_enabled": "Not recommended, default OFF",    
    "chest_joint_enabled": "Recommended unless you have a physical tracker, default ON",
    "spine_upper_joint_enabled": "Not recommended, default OFF",
    "spine_middle_joint_enabled": "Not recommended, default OFF",
    "spine_lower_joint_enabled": "Not recommended, default OFF",
    "hips_joint_enabled": "Useful for hip oriented movement or when using generative legs, default ON",
    "left_shoulder_joint_enabled": "Not recommended, use scaupla if you want shoulder trackers, default OFF",
    "left_scapula_joint_enabled": "Left shoulder tracker, default OFF",
    "left_arm_upper_joint_enabled": "default ON",
    "left_arm_lower_joint_enabled": "default ON",
    "left_hand_wrist_twist_joint_enabled": "Not recommended, default OFF",
    "left_hand_wrist_joint_enabled": "Not recommended, default OFF",
    "left_upper_leg_joint_enabled": "Not recommended, default OFF",
    "left_lower_leg_joint_enabled": "default ON",
    "left_foot_ankle_twist_joint_enabled": "Not recommended, default OFF",
    "left_foot_ankle_joint_enabled": "Not recommended, default OFF",
    "left_foot_subtalar_joint_enabled": "Not recommended, default OFF",
    "left_foot_transverse_joint_enabled": "Left foot tracker, default ON",
    "left_foot_ball_joint_enabled": "Not recommended, default OFF",
    "right_shoulder_joint_enabled": "Not recommended, use scaupla if you want shoulder trackers, default OFF",
    "right_scapula_joint_enabled": "Right shoulder tracker, default OFF",
    "right_arm_upper_joint_enabled": "default ON",
    "right_arm_lower_joint_enabled": "default ON",
    "right_hand_wrist_twist_joint_enabled": "Not recommended, default OFF",
    "right_hand_wrist_joint_enabled": "Not recommended, default OFF",
    "right_upper_leg_joint_enabled": "Not recommended, default OFF",
    "right_lower_leg_joint_enabled": "default ON",
    "right_foot_ankle_twist_joint_enabled": "Not recommended, default OFF",
    "right_foot_ankle_joint_enabled": "Not recommended, default OFF",
    "right_foot_subtalar_joint_enabled": "Not recommended, default OFF",
    "right_foot_transverse_joint_enabled": "Left foot tracker, default ON",
    "right_foot_ball_joint_enabled": "Not recommended, default OFF"
}

tooltips_misc_toggles = {
    "disable_knuckles_rendermodels": "Whether to keep using the Oculus Touch controller models even when emulating Index controllers.",
    "use_trackpad_thumb": "Whether to use Trackpad or A/B touch events for simulating thumb actions."
}

tooltips_misc = {
    "thumb_curl_threshold": "The threshold for simulating a Trackpad or A touch even based on the physical thumb curl.",
    "thumb_curl_full_threshold": "The threshold for simulating a B touch even based on the physical thumb curl",
    "other_fingers_curl_threshold": "The threshold for simulating index/middle/ring/pinky finger curl based on the corresponding physical finger curl.",
    "index_curl_touch_threshold": "The threshold for simulating a trigger touch even based on the physical index curl.",
    "trigger_touch_curl_value": "The value to simulate index finger curl when the controller's trigger touch is detected.\nAlso acts as a threshold for simulating index finger curl based on the physical index curl.",
    "trigger_click_threshold_hand": "The threshold for simulating a trigger click event based on the trigger value, when using hands.",
    "trigger_click_threshold_controller": "The threshold for simulating a trigger click event based on the trigger value, when using a controller.",
    "grip_pinky_curl_threshold": "The threshold for simulating middle/ring/pinky finger curl based on the controller's grip value.",
    "grip_ring_curl_threshold": "The threshold for simulating middle/ring/pinky finger curl based on the controller's grip value.",
    "grip_middle_curl_threshold": "The threshold for simulating middle/ring/pinky finger curl based on the controller's grip value.",
    "grip_force_threshold_hand": "The threshold for simulating grip force based on the grip value, when using hands.",
    "grip_force_threshold_controller": "The threshold for simulating grip force based on the grip value, when using a controller.",
    "hysteresis": "The hysteresis to use for all thresholds."
}